# Generated by Django 5.0.14 on 2026-04-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("studentId", models.CharField(max_length=255)),
                ("jobId", models.CharField(max_length=255)),
                ("appliedAt", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("shortlisted", "shortlisted"),
                            ("rejected", "rejected"),
                            ("accepted", "accepted"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "customResume",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("coverNote", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("companyName", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=255)),
                ("stipend", models.CharField(max_length=255)),
                ("eligibleDepartments", models.JSONField(default=list)),
                ("deadline", models.DateField()),
                ("description", models.TextField()),
                ("postedBy", models.CharField(max_length=255)),
                ("postedAt", models.DateField()),
                ("location", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Full-Time", "Full-Time"),
                            ("Internship", "Internship"),
                            ("Part-Time", "Part-Time"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("sapId", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("department", models.CharField(max_length=255)),
                ("dob", models.DateField()),
                ("score10th", models.FloatField()),
                ("score12th", models.FloatField()),
                ("cgpa", models.FloatField()),
                ("resumeUrl", models.CharField(blank=True, max_length=500, null=True)),
                ("avatar", models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
