# Generated by Django 5.0.14 on 2026-04-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("placements", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recruiter",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("companyName", models.CharField(max_length=255)),
                ("recruiterName", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
