# Generated by Django 5.0.14 on 2026-04-12 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("placements", "0002_recruiter"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruiter",
            name="password",
            field=models.CharField(default="password123", max_length=255),
        ),
    ]
