# Generated by Django 5.0.14 on 2026-04-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("placements", "0003_recruiter_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="jdUrl",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
