# Generated by Django 5.0.14 on 2026-04-12 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("placements", "0004_job_jdurl_alter_job_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="jdUrl",
            field=models.FileField(blank=True, null=True, upload_to="jds/"),
        ),
    ]
