# Generated by Django 5.1.4 on 2026-04-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("placements", "0005_alter_job_jdurl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="customResume",
            field=models.FileField(blank=True, null=True, upload_to="custom_resumes/"),
        ),
        migrations.AlterField(
            model_name="student",
            name="resumeUrl",
            field=models.FileField(blank=True, null=True, upload_to="resumes/"),
        ),
    ]
