# Generated by Django 5.0.14 on 2026-04-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("placements", "0006_alter_application_customresume_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="jdUrl",
            field=models.URLField(blank=True, null=True),
        ),
    ]
