# Generated by Django 5.1.4 on 2026-04-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("placements", "0007_alter_job_jdurl"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="jdPdf",
            field=models.FileField(
                blank=True, null=True, upload_to="job_descriptions/"
            ),
        ),
    ]
