# Generated by Django 5.0.14 on 2026-04-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("placements", "0008_job_jdpdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="password",
            field=models.CharField(default="password123", max_length=255),
        ),
    ]
