# Generated by Django 5.0.14 on 2026-04-13 02:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("placements", "0009_student_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="customResume",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="custom_resume"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="jdPdf",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="job_description"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="resumeUrl",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="resume"
            ),
        ),
    ]
