# Generated by Django 5.0.14 on 2026-04-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("placements", "0010_alter_application_customresume_alter_job_jdpdf_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="sapId",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
