# Generated by Django 5.0.14 on 2026-04-14 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("placements", "0011_alter_student_sapid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruiter",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
