# Generated by Django 5.0.14 on 2026-04-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("placements", "0012_alter_recruiter_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="deadline",
            field=models.CharField(max_length=50),
        ),
    ]
